language: node_js
node_js:
- 12.5.0
cache: npm
services:
  - postgresql
before_script:
- psql -c "CREATE DATABASE postgres;" -U postgres
- psql -c "CREATE USER postgres WITH PASSWORD 'ludacris';" -U postgres